# Generated by Django 3.0.3 on 2020-11-27 10:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='getroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namee', models.CharField(max_length=20)),
                ('koordinatee', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('phnumm', models.IntegerField()),
                ('flooorr', models.CharField(max_length=16)),
                ('roomsnumm', models.IntegerField()),
                ('roomratee', models.IntegerField()),
            ],
        ),
    ]
